-- Update shift_assignments to reference actual employees table
-- Replaces external employee references with internal ones

-- Drop old table and recreate with proper references
DROP TABLE IF EXISTS shift_assignments CASCADE;

CREATE TABLE shift_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id UUID NOT NULL REFERENCES weekly_schedules(id) ON DELETE CASCADE,
  venue_id UUID NOT NULL REFERENCES venues(id) ON DELETE CASCADE,

  -- Employee (now references our employees table)
  employee_id UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  position_id UUID NOT NULL REFERENCES positions(id) ON DELETE CASCADE,

  -- Shift details
  business_date DATE NOT NULL,
  shift_type TEXT NOT NULL CHECK (shift_type IN ('breakfast', 'lunch', 'dinner', 'late_night')),
  scheduled_start TIMESTAMPTZ NOT NULL,
  scheduled_end TIMESTAMPTZ NOT NULL,
  scheduled_hours NUMERIC(4,2) NOT NULL,

  -- Actual times (filled when employee clocks in/out)
  actual_start TIMESTAMPTZ,
  actual_end TIMESTAMPTZ,
  actual_hours NUMERIC(4,2),

  -- Pay
  hourly_rate NUMERIC(6,2),
  scheduled_cost NUMERIC(8,2),
  actual_cost NUMERIC(8,2),

  -- Status
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'confirmed', 'cancelled', 'no_show', 'completed')),

  -- Modifications
  is_modified BOOLEAN DEFAULT FALSE,
  modification_reason TEXT,
  modified_at TIMESTAMPTZ,
  modified_by UUID,

  -- Break tracking
  break_minutes INTEGER DEFAULT 0,

  -- Notes
  notes TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_shift_assignment UNIQUE(schedule_id, employee_id, business_date, scheduled_start)
);

CREATE INDEX idx_assignments_schedule ON shift_assignments(schedule_id);
CREATE INDEX idx_assignments_employee_date ON shift_assignments(employee_id, business_date DESC);
CREATE INDEX idx_assignments_venue_date ON shift_assignments(venue_id, business_date DESC);
CREATE INDEX idx_assignments_position ON shift_assignments(position_id);
CREATE INDEX idx_assignments_status ON shift_assignments(status);

-- Add comments
COMMENT ON TABLE shift_assignments IS 'Individual shift assignments generated by auto-scheduler';
COMMENT ON COLUMN shift_assignments.scheduled_start IS 'Scheduled shift start time (planned)';
COMMENT ON COLUMN shift_assignments.actual_start IS 'Actual clock-in time';
COMMENT ON COLUMN shift_assignments.is_modified IS 'True if shift was changed after initial schedule generation';
