-- Restaurant leads from Restaurant Activity Report
-- Two types: RLR (pre-opening leads) and ERL (existing restaurant database)

-- Pre-opening restaurant leads (RLR)
create table if not exists rar_leads_preopening (
  id bigint primary key generated always as identity,
  source_id integer not null,  -- DataId from RAR
  company text,
  first_name text,
  last_name text,
  title text,
  email text,
  alt_email text,
  phone text,
  cell_phone text,
  extension text,
  other_contact text,
  other_contact_phone text,
  website text,
  facebook text,
  instagram text,
  linkedin text,
  pinterest text,
  address1 text,
  address2 text,
  suite_num text,
  city text,
  state text,
  zip text,
  county text,
  region_name text,
  region_id integer,
  general_area text,
  estimated_open_date text,
  open_month text,
  open_day text,
  open_year text,
  publication_date timestamptz,
  summary text,
  lead_type text,
  lead_type_id integer,
  location_type text,
  location_type_id integer,
  average_check text,
  menu_type text,
  cuisine text,
  meal_period text,
  square_feet integer,
  num_seats integer,
  liquor_license text,
  owner_name text,
  owner_status text,
  former_site text,
  source text,
  google_maps_url text,
  lat double precision,
  lng double precision,
  notes text,
  editorial_notes text,
  phone_interview text,
  phone_notes text,
  data_type integer,
  new_report integer,
  created_on timestamptz,
  fetched_at timestamptz default now(),
  unique(source_id)
);

-- Existing restaurant database (ERL)
create table if not exists rar_leads_existing (
  id bigint primary key generated always as identity,
  source_id integer not null,  -- CompanyID from RAR
  company_unique_id text,
  company_name text,
  company_phone text,
  company_website text,
  facebook_url text,
  instagram_url text,
  linkedin_url text,
  twitter_url text,
  google_map_url text,
  street_address text,
  city text,
  state text,
  state_name text,
  zip text,
  county text,
  country text,
  timezone text,
  latitude double precision,
  longitude double precision,
  mailing_address text,
  mailing_city text,
  mailing_state text,
  mailing_zip text,
  location_type text,
  location_type_id integer,
  menu_type text,
  menu_id integer,
  average_purchase text,
  average_purchase_id integer,
  service_type text,
  service_type_id integer,
  price_level text,
  price_level_id integer,
  open_status text,
  open_status_id integer,
  consumer_rating double precision,
  employee_estimate integer,
  sales_estimate_revenue text,
  total_units integer,
  trade_names text,
  sic_codes integer,
  sic_descriptions text,
  naics_codes integer,
  naics_descriptions text,
  pos_hardware text,
  pos_software text,
  pos_prediction text,
  pos_prediction_description text,
  dun text,
  ein integer,
  contact_first_name text,
  contact_last_name text,
  contact_title text,
  contact_email text,
  contact_phone text,
  entry_date timestamptz,
  date_updated timestamptz,
  is_active boolean,
  notes text,
  fetched_at timestamptz default now(),
  unique(source_id)
);

-- Indexes for common lookups
create index if not exists idx_rar_preopening_state on rar_leads_preopening(state);
create index if not exists idx_rar_preopening_city on rar_leads_preopening(city);
create index if not exists idx_rar_preopening_region on rar_leads_preopening(region_id);
create index if not exists idx_rar_preopening_lead_type on rar_leads_preopening(lead_type_id);
create index if not exists idx_rar_preopening_company on rar_leads_preopening(company);

create index if not exists idx_rar_existing_state on rar_leads_existing(state);
create index if not exists idx_rar_existing_city on rar_leads_existing(city);
create index if not exists idx_rar_existing_company on rar_leads_existing(company_name);
create index if not exists idx_rar_existing_location_type on rar_leads_existing(location_type_id);
create index if not exists idx_rar_existing_open_status on rar_leads_existing(open_status_id);
